### ISSUE TITLE
training data

### ISSUE THREAD

**Issue by Rinisha160391** [junqiangchen/LungLobeSegmentation#2]
Hi,

https://github.com/deep-voxel/automatic_pulmonary_lobe_segmentation_using_deep_learning talks about only the masks data. could please share the source for image data.

Thanks

**Comment by junqiangchen** [comment]
> Hi,
> 
> https://github.com/deep-voxel/automatic_pulmonary_lobe_segmentation_using_deep_learning talks about only the masks data. could please share the source for image data.
> 
> Thanks

you can download source image data from luna16 website

**Comment by RespectKnowledge** [comment]
Dear,
I always saw your repo. This is excellent work. Please could be determined which training samples from luna16 segmentation training samples, I need to acquired. Thanks in advance.

**Comment by anirban1513** [comment]
Yes, can't find the exact images. Which subset they belong? Luna 16 Originally contains a lots of image. @junqiangchen

**Comment by junqiangchen** [comment]
> Dear,
> I always saw your repo. This is excellent work. Please could be determined which training samples from luna16 segmentation training samples, I need to acquired. Thanks in advance.

hi,you can use series id find the luna16 lung samples.

**Comment by anirban1513** [comment]
Hello!

I am getting this error: Image_path_list is Empty. What might be the error?

Traceback (most recent call last):
  File "data3dprepare.py", line 63, in <module>
    preparetraindata()
  File "data3dprepare.py", line 59, in preparetraindata
    preparesampling3dtraindata(heart_imagepath, heart_labelpath,
trainImage, trainMask, (144, 112, 112))
  File "data3dprepare.py", line 12, in preparesampling3dtraindata
    for subsetindex in range(len(image_path_list)):
TypeError: object of type 'NoneType' has no len()
