### ISSUE TITLE
problem in convert_to_onehot in model_vnet3d_multilabel.py

### ISSUE THREAD

**Issue by anirban1513** [junqiangchen/LungLobeSegmentation#5]
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    trainVnet()
  File "train.py", line 31, in trainVnet
    [16, 8])
  File "/home/ubuntu/new_lobe/model_vnet3d_multilabel.py", line 322, in train
    batch_ys_onehot = convert_to_one_hot(batch_ys, self.numclass)
  File "/home/ubuntu/new_lobe/model_vnet3d_multilabel.py", line 190, in convert_to_one_hot
    one_hoty = np.eye(numclass)[one_hoty.reshape(-1).astype(np.int)]
IndexError: index 8 is out of bounds for axis 0 with size 7

**Comment by junqiangchen** [comment]
the number class is 7,but your is 8,there is different.

**Comment by Jishna04** [comment]
I am also having the same issue. I have attached the screenshot. can you please help me with that.[](url
![1](https://user-images.githubusercontent.com/106704405/173330631-33f1b2be-f217-4f4b-bd47-15f3a2cfcaf4.PNG)
)

**Comment by Su0112su** [comment]
> I am also having the same issue. I have attached the screenshot. can you please help me with that.[](url ![1](https://user-images.githubusercontent.com/106704405/173330631-33f1b2be-f217-4f4b-bd47-15f3a2cfcaf4.PNG) )

May I ask how you resolved it?
